server:
    port: 0

spring:
    application:
        name: auth-service
    data:
        mongodb:
            host: 10.1.8.26
            port: 27017
            database: auth-service

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        register-with-eureka: true
        fetch-registry: true

management:
    zipkin:
        tracing:
            endpoint: http://10.1.8.26:9411/api/v2/spans
    tracing:
        sampling:
            probability: 1.0
    endpoints:
        web:
            exposure:
                include: prometheus
logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

