server:
    port: 9001

eureka:
    instance:
        prefer-ip-address: true
        hostname: eureka-0
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://eureka-0.eureka.svc.cluster.local:8761/eureka

spring:
    application:
        name: auth-service
    data:
        mongodb:
            host: mongo
            port: 27017
            database: inwi

management:
    zipkin:
        tracing:
            endpoint: http://zipkin:9411/api/v2/spans
    tracing:
        sampling:
            probability: 1.0
    endpoints:
        web:
            exposure:
                include: prometheus
logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

