apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-service-app
  name: notification-service-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service-app
  strategy: {}
  template:
    metadata:

      labels:
        app: notification-service-app
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: alismak/inwi-notification-service:1.0.0
          name: notification-service-app
          imagePullPolicy: Always
          ports:
            - containerPort: 9003
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service-svc
  name: notification-service-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9003
  selector:
    app: notification-service-app
status:
  loadBalancer: {}
