eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:password@discovery-server:8761/eureka
        register-with-eureka: true
        fetch-registry: true

spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes:
                - id: discovery-server
                  uri: http://eureka:password@discovery-server
                  predicates:
                      - Path=/eureka/web
                  filters:
                      - SetPath=/

                - id: discovery-server-static
                  uri: http://eureka:password@discovery-server:8761
                  predicates:
                      - Path=/eureka/**

                - id: distributer-service
                  uri: lb://DISTRIBUTER-SERVICE
                  predicates:
                      - Path=/api/v1/distributers/**

                - id: reception-service
                  uri: lb://RECEPTION-SERVICE
                  predicates:
                      - Path=/api/v1/receptions/**

                - id: reception-service
                  uri: lb://RECEPTION-SERVICE
                  predicates:
                      - Path=/api/v1/lot/**

                - id: reception-service
                  uri: lb://RECEPTION-SERVICE
                  predicates:
                    - Path=/api/v1/scan/**

                - id: document-service
                  uri: lb://DOCUMENT-SERVICE
                  predicates:
                    - Path=/api/v1/document/**

                - id: producer-association-service
                  uri: lb://PRODUCER-ASSOCIATION-SERVICE
                  predicates:
                    - Path=/api/v1/producer/send
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://keycloak:8080/realms/inwi-management

    management:
        zipkin:
            tracing:
                endpoint: http://kipkin:9411/api/v2/spans
    tracing:
        sampling:
            probability: 1.0
    endpoints:
        web:
            exposure:
                include: prometheus
server:
    port: 8181

logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"